### ISSUE TITLE
Team colors not being recognized.

### ISSUE THREAD

**Issue by CheetoDustBalls** [jwebmeister/tacspeak#28] opened 2024-02-27 01:41 UTC
So I installed this the other day, just about every aspect of the mod works quite well. Except commanding the sub-teams, the mod seems to realllly like commanding red team over gold or blue, I can command red team just fine, but commanding either of the other teams doesn't work, I tried the experimental speech model and got the same results. What I've noticed is the commands are recognized in the console but team specific commands all register back to red team regardless of what I say. I made sure debug mode was set to false as well as noise sink, it's completely silent in my apt besides me speaking and I use a fairly decent headest.
[.tacspeak.log](https://github.com/jwebmeister/tacspeak/files/14413195/default.tacspeak.log)

**Comment by jwebmeister** [comment] 2024-02-27 02:16
I can confirm there's *some* issue with Tacspeak recognising the wrong colour team while speaking commands. For some people it overly recognises "red", for others it's "blue".  
The issue doesn't *always* occur, but it's frequent enough to be annoying.
The issue seems to affect both the "base" model and the "experimental" model, as well as "other experimental" models I've tried (that haven't been released).

There isn't a great work around, but you can try adding a slight pause in your speech after pressing the `listen_key`, before speaking a command.

---

I suspect the issue is being caused by at least one of the following:

1. the `listen_key` enables/disables recognition rules
2. the `listen_key` can purge audio captured prior to being enabled, as well as in other scenarios, potentially losing the start of speech
3. there might be issues caused by timing (CPU)+ audio block size in combination with the above `listen_key` issues

None of these are caused by the models (though there are *other* issues that are caused by the models), and needs to be addressed in [jwebmeister/dragonfly](https://github.com/jwebmeister/dragonfly), specific [issue here](https://github.com/jwebmeister/dragonfly/issues/7)

**Comment by jwebmeister** [comment] 2024-02-27 02:23
Wait @CheetoDustBalls , is your issue that Tacspeak recognises "blue team move there" but it executes in-game "red team move there" command?  
If so, check your keybinds in-game and in Tacspeak (in `_readyornot.py`), check if some other program or mod is conflicting with those keys.

by default in `_readyornot.py`...

```
ingame_key_bindings = {
    "gold": "f5",
    "blue": "f6",
    "red": "f7",
```

**Comment by CheetoDustBalls** [comment] 2024-02-27 23:30
@jwebmeister 
I've disabled all mods on a test, as well as reset to default keybinds. Besides, the only mods other than tacspeak are a gun model replacer and reshade. I do want to say this mod is amazing, everything works besides this one issue.

**Comment by jwebmeister** [comment] 2024-02-28 21:36
@CheetoDustBalls if only selecting blue and gold team isn't working, but other commands are working, try setting other keybinds for selecting blue and gold teams (both in-game and Tacspeak), then test it.  It sounds like you have some other program with conflicting keybinds, e.g. shadowplay, steam overlay, screenshot, etc

**Comment by jwebmeister** [comment] 2024-03-09 01:31
@CheetoDustBalls does the issue still persist after trying with different keybinds?

**Comment by jwebmeister** [comment] 2024-03-14 04:12
I'm closing this issue, assuming that the fix was the OP users specific keybinds and/or resolving other software conflicts.  
The other issue I mentioned in this thread (which is probably unrelated to the OP issue) will be tracked in the dragonfly repo, [specific issue here](https://github.com/jwebmeister/dragonfly/issues/7)

**Closed as completed by jwebmeister** 2024-03-14 04:12 UTC
